In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gc 
from sklearn.metrics import f1_score
import json

import sys
import os

sys.path.append(os.path.abspath(os.path.join('..')))

from src.load_data_gait import *
from src.plot_data_gait import *
from src.train_LSTMGait import train_model, predict_trial

In [2]:
base_path = '../datasets/GAIT_signals/dataset/data'

# Training

In [3]:
results = []
results_path = "../checkpoints/grid_search_results.json"

if os.path.exists(results_path):
    with open(results_path) as f:
        results = json.load(f)

done_keys = {(r["win_size"], r["stride"], r["process"], r["norm"]) for r in results}

for win_size in [50, 100, 200, 400, 500, 700]:
    for overlap in [0, 0.25, 0.5, 0.75]:
        stride = win_size if overlap == 0 else int(win_size * (1 - overlap))

        for process in ["raw", "free_raw"]:
            for norm in ["window", "subj"]:
                key = (win_size, stride, process, norm)
                if key in done_keys:
                    print(f"Skipping already-done combo: win_size={win_size}, stride={stride}, process={process}, norm={norm}")
                    continue

                print(f"Processing with win_size={win_size}, stride={stride}, process={process}, norm={norm}")
                X, y, subjects = load_dataset_gait(base_path, process=process, sensors=['LB'], window_size=win_size, stride=stride)
                X = X.astype(np.float32)
                y = y.astype(np.int64)

                ckpt_path = f"../checkpoints/{process}_win{win_size}_stride{stride}_norm{norm}"
                trained_model, best_val_f1, test_f1 = train_model(X, y, subjects, model_name="cnnbilstm", norm=norm, epochs=200, lr=0.001, patience=20, out_dir=ckpt_path)

                n_subjects = len(np.unique(subjects))
                n_windows = X.shape[0]

                results.append({
                    "win_size": win_size,
                    "stride": stride,
                    "overlap": overlap,
                    "process": process,
                    "norm": norm,
                    "n_subjects": n_subjects,
                    "n_windows": n_windows,
                    "val_f1": round(float(best_val_f1), 6),
                    "test_f1": round(float(test_f1), 6),
                    "checkpoint": ckpt_path,
                })
                print("")
                print("================================")
                print("")

                with open(results_path, 'w') as f:
                    json.dump(results, f, indent=2)

                del X, y, subjects, trained_model
                gc.collect()

print(f"\nDone. {len(results)} combinations trained.")

Processing with win_size=50, stride=50, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 62085  |  test: 17793
               →  train: 166 subjects (48324 windows)  |  val: 42 subjects (13761 windows)

Early stopping in epoch 47. Best F1: 0.8901

Val F1: 0.8901  |  Test F1: 0.8643
Checkpoint saved → ../checkpoints/raw_win50_stride50_normwindow\model.pt

================================

Processing with win_size=50, stride=50, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 62085  |  test: 17793
               →  train: 166 subjects (48324 windows)  |  val: 42 subjects (13761 windows)

Early stopping in epoch 52. Best F1: 0.8866

Val F1: 0.8866  |  Test F1: 0.8659
Checkpoint saved → ../checkpoints/raw_win50_stride50_normsubj\model.pt

================================

Processing with win_size=50, stride=50, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 62085  |  test: 17793
               →  train: 166 subjects (48324 windows)  |  val: 42 subjects (13761 windows)

Early stopping in epoch 41. Best F1: 0.8876

Val F1: 0.8876  |  Test F1: 0.8568
Checkpoint saved → ../checkpoints/free_raw_win50_stride50_normwindow\model.pt

================================

Processing with win_size=50, stride=50, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 62085  |  test: 17793
               →  train: 166 subjects (48324 windows)  |  val: 42 subjects (13761 windows)

Early stopping in epoch 59. Best F1: 0.8941

Val F1: 0.8941  |  Test F1: 0.8689
Checkpoint saved → ../checkpoints/free_raw_win50_stride50_normsubj\model.pt

================================

Processing with win_size=50, stride=37, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 83698  |  test: 24004
               →  train: 166 subjects (65155 windows)  |  val: 42 subjects (18543 windows)

Early stopping in epoch 62. Best F1: 0.8937

Val F1: 0.8937  |  Test F1: 0.8630
Checkpoint saved → ../checkpoints/raw_win50_stride37_normwindow\model.pt

================================

Processing with win_size=50, stride=37, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 83698  |  test: 24004
               →  train: 166 subjects (65155 windows)  |  val: 42 subjects (18543 windows)

Early stopping in epoch 52. Best F1: 0.8921

Val F1: 0.8921  |  Test F1: 0.8621
Checkpoint saved → ../checkpoints/raw_win50_stride37_normsubj\model.pt

================================

Processing with win_size=50, stride=37, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 83698  |  test: 24004
               →  train: 166 subjects (65155 windows)  |  val: 42 subjects (18543 windows)

Early stopping in epoch 51. Best F1: 0.8936

Val F1: 0.8936  |  Test F1: 0.8666
Checkpoint saved → ../checkpoints/free_raw_win50_stride37_normwindow\model.pt

================================

Processing with win_size=50, stride=37, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 83698  |  test: 24004
               →  train: 166 subjects (65155 windows)  |  val: 42 subjects (18543 windows)

Early stopping in epoch 51. Best F1: 0.8950

Val F1: 0.8950  |  Test F1: 0.8756
Checkpoint saved → ../checkpoints/free_raw_win50_stride37_normsubj\model.pt

================================

Processing with win_size=50, stride=25, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 123623  |  test: 35468
               →  train: 166 subjects (96226 windows)  |  val: 42 subjects (27397 windows)

Early stopping in epoch 60. Best F1: 0.8983

Val F1: 0.8983  |  Test F1: 0.8764
Checkpoint saved → ../checkpoints/raw_win50_stride25_normwindow\model.pt

================================

Processing with win_size=50, stride=25, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 123623  |  test: 35468
               →  train: 166 subjects (96226 windows)  |  val: 42 subjects (27397 windows)

Early stopping in epoch 47. Best F1: 0.8943

Val F1: 0.8943  |  Test F1: 0.8661
Checkpoint saved → ../checkpoints/raw_win50_stride25_normsubj\model.pt

================================

Processing with win_size=50, stride=25, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 123623  |  test: 35468
               →  train: 166 subjects (96226 windows)  |  val: 42 subjects (27397 windows)

Early stopping in epoch 61. Best F1: 0.8964

Val F1: 0.8964  |  Test F1: 0.8710
Checkpoint saved → ../checkpoints/free_raw_win50_stride25_normwindow\model.pt

================================

Processing with win_size=50, stride=25, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 123623  |  test: 35468
               →  train: 166 subjects (96226 windows)  |  val: 42 subjects (27397 windows)

Early stopping in epoch 57. Best F1: 0.8965

Val F1: 0.8965  |  Test F1: 0.8735
Checkpoint saved → ../checkpoints/free_raw_win50_stride25_normsubj\model.pt

================================

Processing with win_size=50, stride=12, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 256986  |  test: 73731
               →  train: 166 subjects (200034 windows)  |  val: 42 subjects (56952 windows)

Early stopping in epoch 70. Best F1: 0.9004

Val F1: 0.9004  |  Test F1: 0.8784
Checkpoint saved → ../checkpoints/raw_win50_stride12_normwindow\model.pt

================================

Processing with win_size=50, stride=12, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 256986  |  test: 73731
               →  train: 166 subjects (200034 windows)  |  val: 42 subjects (56952 windows)

Early stopping in epoch 47. Best F1: 0.8970

Val F1: 0.8970  |  Test F1: 0.8714
Checkpoint saved → ../checkpoints/raw_win50_stride12_normsubj\model.pt

================================

Processing with win_size=50, stride=12, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 256986  |  test: 73731
               →  train: 166 subjects (200034 windows)  |  val: 42 subjects (56952 windows)

Early stopping in epoch 55. Best F1: 0.9014

Val F1: 0.9014  |  Test F1: 0.8810
Checkpoint saved → ../checkpoints/free_raw_win50_stride12_normwindow\model.pt

================================

Processing with win_size=50, stride=12, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 256986  |  test: 73731
               →  train: 166 subjects (200034 windows)  |  val: 42 subjects (56952 windows)

Early stopping in epoch 42. Best F1: 0.8980

Val F1: 0.8980  |  Test F1: 0.8700
Checkpoint saved → ../checkpoints/free_raw_win50_stride12_normsubj\model.pt

================================

Processing with win_size=100, stride=100, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 30771  |  test: 8829
               →  train: 166 subjects (23954 windows)  |  val: 42 subjects (6817 windows)

Early stopping in epoch 71. Best F1: 0.9055

Val F1: 0.9055  |  Test F1: 0.8800
Checkpoint saved → ../checkpoints/raw_win100_stride100_normwindow\model.pt

================================

Processing with win_size=100, stride=100, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 30771  |  test: 8829
               →  train: 166 subjects (23954 windows)  |  val: 42 subjects (6817 windows)

Early stopping in epoch 46. Best F1: 0.8983

Val F1: 0.8983  |  Test F1: 0.8699
Checkpoint saved → ../checkpoints/raw_win100_stride100_normsubj\model.pt

================================

Processing with win_size=100, stride=100, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 30771  |  test: 8829
               →  train: 166 subjects (23954 windows)  |  val: 42 subjects (6817 windows)

Early stopping in epoch 51. Best F1: 0.9056

Val F1: 0.9056  |  Test F1: 0.8775
Checkpoint saved → ../checkpoints/free_raw_win100_stride100_normwindow\model.pt

================================

Processing with win_size=100, stride=100, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 30771  |  test: 8829
               →  train: 166 subjects (23954 windows)  |  val: 42 subjects (6817 windows)

Early stopping in epoch 51. Best F1: 0.9027

Val F1: 0.9027  |  Test F1: 0.8786
Checkpoint saved → ../checkpoints/free_raw_win100_stride100_normsubj\model.pt

================================

Processing with win_size=100, stride=75, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 40835  |  test: 11741
               →  train: 166 subjects (31787 windows)  |  val: 42 subjects (9048 windows)

Early stopping in epoch 52. Best F1: 0.9088

Val F1: 0.9088  |  Test F1: 0.8820
Checkpoint saved → ../checkpoints/raw_win100_stride75_normwindow\model.pt

================================

Processing with win_size=100, stride=75, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 40835  |  test: 11741
               →  train: 166 subjects (31787 windows)  |  val: 42 subjects (9048 windows)

Early stopping in epoch 53. Best F1: 0.9026

Val F1: 0.9026  |  Test F1: 0.8629
Checkpoint saved → ../checkpoints/raw_win100_stride75_normsubj\model.pt

================================

Processing with win_size=100, stride=75, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 40835  |  test: 11741
               →  train: 166 subjects (31787 windows)  |  val: 42 subjects (9048 windows)

Early stopping in epoch 41. Best F1: 0.9074

Val F1: 0.9074  |  Test F1: 0.8823
Checkpoint saved → ../checkpoints/free_raw_win100_stride75_normwindow\model.pt

================================

Processing with win_size=100, stride=75, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 40835  |  test: 11741
               →  train: 166 subjects (31787 windows)  |  val: 42 subjects (9048 windows)

Early stopping in epoch 53. Best F1: 0.9073

Val F1: 0.9073  |  Test F1: 0.8781
Checkpoint saved → ../checkpoints/free_raw_win100_stride75_normsubj\model.pt

================================

Processing with win_size=100, stride=50, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 61005  |  test: 17527
               →  train: 166 subjects (47489 windows)  |  val: 42 subjects (13516 windows)

Early stopping in epoch 40. Best F1: 0.9095

Val F1: 0.9095  |  Test F1: 0.8873
Checkpoint saved → ../checkpoints/raw_win100_stride50_normwindow\model.pt

================================

Processing with win_size=100, stride=50, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 61005  |  test: 17527
               →  train: 166 subjects (47489 windows)  |  val: 42 subjects (13516 windows)

Early stopping in epoch 60. Best F1: 0.9019

Val F1: 0.9019  |  Test F1: 0.8713
Checkpoint saved → ../checkpoints/raw_win100_stride50_normsubj\model.pt

================================

Processing with win_size=100, stride=50, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 61005  |  test: 17527
               →  train: 166 subjects (47489 windows)  |  val: 42 subjects (13516 windows)

Early stopping in epoch 56. Best F1: 0.9120

Val F1: 0.9120  |  Test F1: 0.8886
Checkpoint saved → ../checkpoints/free_raw_win100_stride50_normwindow\model.pt

================================

Processing with win_size=100, stride=50, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 61005  |  test: 17527
               →  train: 166 subjects (47489 windows)  |  val: 42 subjects (13516 windows)

Early stopping in epoch 44. Best F1: 0.9034

Val F1: 0.9034  |  Test F1: 0.8771
Checkpoint saved → ../checkpoints/free_raw_win100_stride50_normsubj\model.pt

================================

Processing with win_size=100, stride=25, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 121463  |  test: 34936
               →  train: 166 subjects (94556 windows)  |  val: 42 subjects (26907 windows)

Early stopping in epoch 61. Best F1: 0.9134

Val F1: 0.9134  |  Test F1: 0.8940
Checkpoint saved → ../checkpoints/raw_win100_stride25_normwindow\model.pt

================================

Processing with win_size=100, stride=25, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 121463  |  test: 34936
               →  train: 166 subjects (94556 windows)  |  val: 42 subjects (26907 windows)

Early stopping in epoch 53. Best F1: 0.9047

Val F1: 0.9047  |  Test F1: 0.8747
Checkpoint saved → ../checkpoints/raw_win100_stride25_normsubj\model.pt

================================

Processing with win_size=100, stride=25, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 121463  |  test: 34936
               →  train: 166 subjects (94556 windows)  |  val: 42 subjects (26907 windows)

Early stopping in epoch 57. Best F1: 0.9135

Val F1: 0.9135  |  Test F1: 0.8904
Checkpoint saved → ../checkpoints/free_raw_win100_stride25_normwindow\model.pt

================================

Processing with win_size=100, stride=25, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 121463  |  test: 34936
               →  train: 166 subjects (94556 windows)  |  val: 42 subjects (26907 windows)

Early stopping in epoch 43. Best F1: 0.9073

Val F1: 0.9073  |  Test F1: 0.8833
Checkpoint saved → ../checkpoints/free_raw_win100_stride25_normsubj\model.pt

================================

Processing with win_size=200, stride=200, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 15125  |  test: 4347
               →  train: 166 subjects (11770 windows)  |  val: 42 subjects (3355 windows)

Early stopping in epoch 71. Best F1: 0.9103

Val F1: 0.9103  |  Test F1: 0.8879
Checkpoint saved → ../checkpoints/raw_win200_stride200_normwindow\model.pt

================================

Processing with win_size=200, stride=200, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 15125  |  test: 4347
               →  train: 166 subjects (11770 windows)  |  val: 42 subjects (3355 windows)

Early stopping in epoch 35. Best F1: 0.9004

Val F1: 0.9004  |  Test F1: 0.8681
Checkpoint saved → ../checkpoints/raw_win200_stride200_normsubj\model.pt

================================

Processing with win_size=200, stride=200, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 15125  |  test: 4347
               →  train: 166 subjects (11770 windows)  |  val: 42 subjects (3355 windows)

Early stopping in epoch 55. Best F1: 0.9118

Val F1: 0.9118  |  Test F1: 0.8870
Checkpoint saved → ../checkpoints/free_raw_win200_stride200_normwindow\model.pt

================================

Processing with win_size=200, stride=200, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 15125  |  test: 4347
               →  train: 166 subjects (11770 windows)  |  val: 42 subjects (3355 windows)

Early stopping in epoch 40. Best F1: 0.9077

Val F1: 0.9077  |  Test F1: 0.8856
Checkpoint saved → ../checkpoints/free_raw_win200_stride200_normsubj\model.pt

================================

Processing with win_size=200, stride=150, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 19982  |  test: 5750
               →  train: 166 subjects (15554 windows)  |  val: 42 subjects (4428 windows)

Early stopping in epoch 65. Best F1: 0.9134

Val F1: 0.9134  |  Test F1: 0.8829
Checkpoint saved → ../checkpoints/raw_win200_stride150_normwindow\model.pt

================================

Processing with win_size=200, stride=150, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 19982  |  test: 5750
               →  train: 166 subjects (15554 windows)  |  val: 42 subjects (4428 windows)

Early stopping in epoch 38. Best F1: 0.9038

Val F1: 0.9038  |  Test F1: 0.8720
Checkpoint saved → ../checkpoints/raw_win200_stride150_normsubj\model.pt

================================

Processing with win_size=200, stride=150, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 19982  |  test: 5750
               →  train: 166 subjects (15554 windows)  |  val: 42 subjects (4428 windows)

Early stopping in epoch 43. Best F1: 0.9153

Val F1: 0.9153  |  Test F1: 0.8879
Checkpoint saved → ../checkpoints/free_raw_win200_stride150_normwindow\model.pt

================================

Processing with win_size=200, stride=150, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 19982  |  test: 5750
               →  train: 166 subjects (15554 windows)  |  val: 42 subjects (4428 windows)

Early stopping in epoch 35. Best F1: 0.9086

Val F1: 0.9086  |  Test F1: 0.8861
Checkpoint saved → ../checkpoints/free_raw_win200_stride150_normsubj\model.pt

================================

Processing with win_size=200, stride=100, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 29691  |  test: 8563
               →  train: 166 subjects (23119 windows)  |  val: 42 subjects (6572 windows)

Early stopping in epoch 53. Best F1: 0.9151

Val F1: 0.9151  |  Test F1: 0.8900
Checkpoint saved → ../checkpoints/raw_win200_stride100_normwindow\model.pt

================================

Processing with win_size=200, stride=100, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 29691  |  test: 8563
               →  train: 166 subjects (23119 windows)  |  val: 42 subjects (6572 windows)

Early stopping in epoch 35. Best F1: 0.8993

Val F1: 0.8993  |  Test F1: 0.8724
Checkpoint saved → ../checkpoints/raw_win200_stride100_normsubj\model.pt

================================

Processing with win_size=200, stride=100, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 29691  |  test: 8563
               →  train: 166 subjects (23119 windows)  |  val: 42 subjects (6572 windows)

Early stopping in epoch 53. Best F1: 0.9158

Val F1: 0.9158  |  Test F1: 0.8874
Checkpoint saved → ../checkpoints/free_raw_win200_stride100_normwindow\model.pt

================================

Processing with win_size=200, stride=100, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 29691  |  test: 8563
               →  train: 166 subjects (23119 windows)  |  val: 42 subjects (6572 windows)

Early stopping in epoch 31. Best F1: 0.9069

Val F1: 0.9069  |  Test F1: 0.8863
Checkpoint saved → ../checkpoints/free_raw_win200_stride100_normsubj\model.pt

================================

Processing with win_size=200, stride=50, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 58845  |  test: 16995
               →  train: 166 subjects (45819 windows)  |  val: 42 subjects (13026 windows)

Early stopping in epoch 65. Best F1: 0.9168

Val F1: 0.9168  |  Test F1: 0.8952
Checkpoint saved → ../checkpoints/raw_win200_stride50_normwindow\model.pt

================================

Processing with win_size=200, stride=50, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 58845  |  test: 16995
               →  train: 166 subjects (45819 windows)  |  val: 42 subjects (13026 windows)

Early stopping in epoch 39. Best F1: 0.9066

Val F1: 0.9066  |  Test F1: 0.8793
Checkpoint saved → ../checkpoints/raw_win200_stride50_normsubj\model.pt

================================

Processing with win_size=200, stride=50, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 58845  |  test: 16995
               →  train: 166 subjects (45819 windows)  |  val: 42 subjects (13026 windows)

Early stopping in epoch 39. Best F1: 0.9167

Val F1: 0.9167  |  Test F1: 0.8948
Checkpoint saved → ../checkpoints/free_raw_win200_stride50_normwindow\model.pt

================================

Processing with win_size=200, stride=50, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 58845  |  test: 16995
               →  train: 166 subjects (45819 windows)  |  val: 42 subjects (13026 windows)

Early stopping in epoch 45. Best F1: 0.9104

Val F1: 0.9104  |  Test F1: 0.8859
Checkpoint saved → ../checkpoints/free_raw_win200_stride50_normsubj\model.pt

================================

Processing with win_size=400, stride=400, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7289  |  test: 2107
               →  train: 166 subjects (5670 windows)  |  val: 42 subjects (1619 windows)

Early stopping in epoch 57. Best F1: 0.9131

Val F1: 0.9131  |  Test F1: 0.8883
Checkpoint saved → ../checkpoints/raw_win400_stride400_normwindow\model.pt

================================

Processing with win_size=400, stride=400, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7289  |  test: 2107
               →  train: 166 subjects (5670 windows)  |  val: 42 subjects (1619 windows)

Early stopping in epoch 59. Best F1: 0.9055

Val F1: 0.9055  |  Test F1: 0.8699
Checkpoint saved → ../checkpoints/raw_win400_stride400_normsubj\model.pt

================================

Processing with win_size=400, stride=400, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7289  |  test: 2107
               →  train: 166 subjects (5670 windows)  |  val: 42 subjects (1619 windows)

Early stopping in epoch 70. Best F1: 0.9135

Val F1: 0.9135  |  Test F1: 0.8920
Checkpoint saved → ../checkpoints/free_raw_win400_stride400_normwindow\model.pt

================================

Processing with win_size=400, stride=400, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7289  |  test: 2107
               →  train: 166 subjects (5670 windows)  |  val: 42 subjects (1619 windows)

Early stopping in epoch 68. Best F1: 0.9080

Val F1: 0.9080  |  Test F1: 0.8776
Checkpoint saved → ../checkpoints/free_raw_win400_stride400_normsubj\model.pt

================================

Processing with win_size=400, stride=300, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 9536  |  test: 2762
               →  train: 166 subjects (7425 windows)  |  val: 42 subjects (2111 windows)

Early stopping in epoch 64. Best F1: 0.9144

Val F1: 0.9144  |  Test F1: 0.8876
Checkpoint saved → ../checkpoints/raw_win400_stride300_normwindow\model.pt

================================

Processing with win_size=400, stride=300, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 9536  |  test: 2762
               →  train: 166 subjects (7425 windows)  |  val: 42 subjects (2111 windows)

Early stopping in epoch 42. Best F1: 0.9019

Val F1: 0.9019  |  Test F1: 0.8643
Checkpoint saved → ../checkpoints/raw_win400_stride300_normsubj\model.pt

================================

Processing with win_size=400, stride=300, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 9536  |  test: 2762
               →  train: 166 subjects (7425 windows)  |  val: 42 subjects (2111 windows)

Early stopping in epoch 67. Best F1: 0.9162

Val F1: 0.9162  |  Test F1: 0.8902
Checkpoint saved → ../checkpoints/free_raw_win400_stride300_normwindow\model.pt

================================

Processing with win_size=400, stride=300, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 9536  |  test: 2762
               →  train: 166 subjects (7425 windows)  |  val: 42 subjects (2111 windows)

Early stopping in epoch 57. Best F1: 0.9114

Val F1: 0.9114  |  Test F1: 0.8794
Checkpoint saved → ../checkpoints/free_raw_win400_stride300_normsubj\model.pt

================================

Processing with win_size=400, stride=200, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14045  |  test: 4081
               →  train: 166 subjects (10935 windows)  |  val: 42 subjects (3110 windows)

Early stopping in epoch 58. Best F1: 0.9171

Val F1: 0.9171  |  Test F1: 0.8880
Checkpoint saved → ../checkpoints/raw_win400_stride200_normwindow\model.pt

================================

Processing with win_size=400, stride=200, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14045  |  test: 4081
               →  train: 166 subjects (10935 windows)  |  val: 42 subjects (3110 windows)

Early stopping in epoch 37. Best F1: 0.9010

Val F1: 0.9010  |  Test F1: 0.8711
Checkpoint saved → ../checkpoints/raw_win400_stride200_normsubj\model.pt

================================

Processing with win_size=400, stride=200, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14045  |  test: 4081
               →  train: 166 subjects (10935 windows)  |  val: 42 subjects (3110 windows)

Early stopping in epoch 53. Best F1: 0.9149

Val F1: 0.9149  |  Test F1: 0.8830
Checkpoint saved → ../checkpoints/free_raw_win400_stride200_normwindow\model.pt

================================

Processing with win_size=400, stride=200, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14045  |  test: 4081
               →  train: 166 subjects (10935 windows)  |  val: 42 subjects (3110 windows)

Early stopping in epoch 54. Best F1: 0.9107

Val F1: 0.9107  |  Test F1: 0.8859
Checkpoint saved → ../checkpoints/free_raw_win400_stride200_normsubj\model.pt

================================

Processing with win_size=400, stride=100, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 27531  |  test: 8031
               →  train: 166 subjects (21449 windows)  |  val: 42 subjects (6082 windows)

Early stopping in epoch 50. Best F1: 0.9173

Val F1: 0.9173  |  Test F1: 0.8885
Checkpoint saved → ../checkpoints/raw_win400_stride100_normwindow\model.pt

================================

Processing with win_size=400, stride=100, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 27531  |  test: 8031
               →  train: 166 subjects (21449 windows)  |  val: 42 subjects (6082 windows)

Early stopping in epoch 79. Best F1: 0.9040

Val F1: 0.9040  |  Test F1: 0.8744
Checkpoint saved → ../checkpoints/raw_win400_stride100_normsubj\model.pt

================================

Processing with win_size=400, stride=100, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 27531  |  test: 8031
               →  train: 166 subjects (21449 windows)  |  val: 42 subjects (6082 windows)

Early stopping in epoch 39. Best F1: 0.9151

Val F1: 0.9151  |  Test F1: 0.8915
Checkpoint saved → ../checkpoints/free_raw_win400_stride100_normwindow\model.pt

================================

Processing with win_size=400, stride=100, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 27531  |  test: 8031
               →  train: 166 subjects (21449 windows)  |  val: 42 subjects (6082 windows)

Early stopping in epoch 44. Best F1: 0.9072

Val F1: 0.9072  |  Test F1: 0.8842
Checkpoint saved → ../checkpoints/free_raw_win400_stride100_normsubj\model.pt

================================

Processing with win_size=500, stride=500, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5725  |  test: 1658
               →  train: 166 subjects (4455 windows)  |  val: 42 subjects (1270 windows)

Early stopping in epoch 73. Best F1: 0.9157

Val F1: 0.9157  |  Test F1: 0.8875
Checkpoint saved → ../checkpoints/raw_win500_stride500_normwindow\model.pt

================================

Processing with win_size=500, stride=500, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5725  |  test: 1658
               →  train: 166 subjects (4455 windows)  |  val: 42 subjects (1270 windows)

Early stopping in epoch 72. Best F1: 0.8989

Val F1: 0.8989  |  Test F1: 0.8739
Checkpoint saved → ../checkpoints/raw_win500_stride500_normsubj\model.pt

================================

Processing with win_size=500, stride=500, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5725  |  test: 1658
               →  train: 166 subjects (4455 windows)  |  val: 42 subjects (1270 windows)

Early stopping in epoch 68. Best F1: 0.9149

Val F1: 0.9149  |  Test F1: 0.8846
Checkpoint saved → ../checkpoints/free_raw_win500_stride500_normwindow\model.pt

================================

Processing with win_size=500, stride=500, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5725  |  test: 1658
               →  train: 166 subjects (4455 windows)  |  val: 42 subjects (1270 windows)

Early stopping in epoch 51. Best F1: 0.9087

Val F1: 0.9087  |  Test F1: 0.8769
Checkpoint saved → ../checkpoints/free_raw_win500_stride500_normsubj\model.pt

================================

Processing with win_size=500, stride=375, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7452  |  test: 2168
               →  train: 166 subjects (5803 windows)  |  val: 42 subjects (1649 windows)

Early stopping in epoch 69. Best F1: 0.9144

Val F1: 0.9144  |  Test F1: 0.8896
Checkpoint saved → ../checkpoints/raw_win500_stride375_normwindow\model.pt

================================

Processing with win_size=500, stride=375, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7452  |  test: 2168
               →  train: 166 subjects (5803 windows)  |  val: 42 subjects (1649 windows)

Early stopping in epoch 36. Best F1: 0.8939

Val F1: 0.8939  |  Test F1: 0.8699
Checkpoint saved → ../checkpoints/raw_win500_stride375_normsubj\model.pt

================================

Processing with win_size=500, stride=375, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7452  |  test: 2168
               →  train: 166 subjects (5803 windows)  |  val: 42 subjects (1649 windows)

Early stopping in epoch 67. Best F1: 0.9144

Val F1: 0.9144  |  Test F1: 0.8902
Checkpoint saved → ../checkpoints/free_raw_win500_stride375_normwindow\model.pt

================================

Processing with win_size=500, stride=375, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7452  |  test: 2168
               →  train: 166 subjects (5803 windows)  |  val: 42 subjects (1649 windows)

Early stopping in epoch 73. Best F1: 0.9087

Val F1: 0.9087  |  Test F1: 0.8812
Checkpoint saved → ../checkpoints/free_raw_win500_stride375_normsubj\model.pt

================================

Processing with win_size=500, stride=250, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 10906  |  test: 3184
               →  train: 166 subjects (8496 windows)  |  val: 42 subjects (2410 windows)

Early stopping in epoch 60. Best F1: 0.9150

Val F1: 0.9150  |  Test F1: 0.8915
Checkpoint saved → ../checkpoints/raw_win500_stride250_normwindow\model.pt

================================

Processing with win_size=500, stride=250, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 10906  |  test: 3184
               →  train: 166 subjects (8496 windows)  |  val: 42 subjects (2410 windows)

Early stopping in epoch 32. Best F1: 0.8959

Val F1: 0.8959  |  Test F1: 0.8608
Checkpoint saved → ../checkpoints/raw_win500_stride250_normsubj\model.pt

================================

Processing with win_size=500, stride=250, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 10906  |  test: 3184
               →  train: 166 subjects (8496 windows)  |  val: 42 subjects (2410 windows)

Early stopping in epoch 48. Best F1: 0.9153

Val F1: 0.9153  |  Test F1: 0.8881
Checkpoint saved → ../checkpoints/free_raw_win500_stride250_normwindow\model.pt

================================

Processing with win_size=500, stride=250, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 10906  |  test: 3184
               →  train: 166 subjects (8496 windows)  |  val: 42 subjects (2410 windows)

Early stopping in epoch 43. Best F1: 0.9093

Val F1: 0.9093  |  Test F1: 0.8732
Checkpoint saved → ../checkpoints/free_raw_win500_stride250_normsubj\model.pt

================================

Processing with win_size=500, stride=125, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 21259  |  test: 6239
               →  train: 166 subjects (16567 windows)  |  val: 42 subjects (4692 windows)

Early stopping in epoch 60. Best F1: 0.9147

Val F1: 0.9147  |  Test F1: 0.8933
Checkpoint saved → ../checkpoints/raw_win500_stride125_normwindow\model.pt

================================

Processing with win_size=500, stride=125, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 21259  |  test: 6239
               →  train: 166 subjects (16567 windows)  |  val: 42 subjects (4692 windows)

Early stopping in epoch 29. Best F1: 0.8960

Val F1: 0.8960  |  Test F1: 0.8695
Checkpoint saved → ../checkpoints/raw_win500_stride125_normsubj\model.pt

================================

Processing with win_size=500, stride=125, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 21259  |  test: 6239
               →  train: 166 subjects (16567 windows)  |  val: 42 subjects (4692 windows)

Early stopping in epoch 54. Best F1: 0.9150

Val F1: 0.9150  |  Test F1: 0.8902
Checkpoint saved → ../checkpoints/free_raw_win500_stride125_normwindow\model.pt

================================

Processing with win_size=500, stride=125, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 21259  |  test: 6239
               →  train: 166 subjects (16567 windows)  |  val: 42 subjects (4692 windows)

Early stopping in epoch 41. Best F1: 0.9102

Val F1: 0.9102  |  Test F1: 0.8816
Checkpoint saved → ../checkpoints/free_raw_win500_stride125_normsubj\model.pt

================================

Processing with win_size=700, stride=700, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 3936  |  test: 1150
               →  train: 166 subjects (3065 windows)  |  val: 42 subjects (871 windows)

Early stopping in epoch 66. Best F1: 0.9118

Val F1: 0.9118  |  Test F1: 0.8851
Checkpoint saved → ../checkpoints/raw_win700_stride700_normwindow\model.pt

================================

Processing with win_size=700, stride=700, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 3936  |  test: 1150
               →  train: 166 subjects (3065 windows)  |  val: 42 subjects (871 windows)

Early stopping in epoch 38. Best F1: 0.8987

Val F1: 0.8987  |  Test F1: 0.8642
Checkpoint saved → ../checkpoints/raw_win700_stride700_normsubj\model.pt

================================

Processing with win_size=700, stride=700, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 3936  |  test: 1150
               →  train: 166 subjects (3065 windows)  |  val: 42 subjects (871 windows)

Early stopping in epoch 101. Best F1: 0.9115

Val F1: 0.9115  |  Test F1: 0.8840
Checkpoint saved → ../checkpoints/free_raw_win700_stride700_normwindow\model.pt

================================

Processing with win_size=700, stride=700, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 3936  |  test: 1150
               →  train: 166 subjects (3065 windows)  |  val: 42 subjects (871 windows)

Early stopping in epoch 83. Best F1: 0.9092

Val F1: 0.9092  |  Test F1: 0.8793
Checkpoint saved → ../checkpoints/free_raw_win700_stride700_normsubj\model.pt

================================

Processing with win_size=700, stride=525, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5075  |  test: 1485
               →  train: 166 subjects (3954 windows)  |  val: 42 subjects (1121 windows)

Early stopping in epoch 68. Best F1: 0.9120

Val F1: 0.9120  |  Test F1: 0.8858
Checkpoint saved → ../checkpoints/raw_win700_stride525_normwindow\model.pt

================================

Processing with win_size=700, stride=525, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5075  |  test: 1485
               →  train: 166 subjects (3954 windows)  |  val: 42 subjects (1121 windows)

Early stopping in epoch 51. Best F1: 0.8971

Val F1: 0.8971  |  Test F1: 0.8684
Checkpoint saved → ../checkpoints/raw_win700_stride525_normsubj\model.pt

================================

Processing with win_size=700, stride=525, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5075  |  test: 1485
               →  train: 166 subjects (3954 windows)  |  val: 42 subjects (1121 windows)

Early stopping in epoch 68. Best F1: 0.9130

Val F1: 0.9130  |  Test F1: 0.8828
Checkpoint saved → ../checkpoints/free_raw_win700_stride525_normwindow\model.pt

================================

Processing with win_size=700, stride=525, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 5075  |  test: 1485
               →  train: 166 subjects (3954 windows)  |  val: 42 subjects (1121 windows)

Early stopping in epoch 40. Best F1: 0.9057

Val F1: 0.9057  |  Test F1: 0.8796
Checkpoint saved → ../checkpoints/free_raw_win700_stride525_normsubj\model.pt

================================

Processing with win_size=700, stride=350, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7324  |  test: 2162
               →  train: 166 subjects (5702 windows)  |  val: 42 subjects (1622 windows)

Early stopping in epoch 98. Best F1: 0.9119

Val F1: 0.9119  |  Test F1: 0.8833
Checkpoint saved → ../checkpoints/raw_win700_stride350_normwindow\model.pt

================================

Processing with win_size=700, stride=350, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7324  |  test: 2162
               →  train: 166 subjects (5702 windows)  |  val: 42 subjects (1622 windows)

Early stopping in epoch 48. Best F1: 0.8955

Val F1: 0.8955  |  Test F1: 0.8578
Checkpoint saved → ../checkpoints/raw_win700_stride350_normsubj\model.pt

================================

Processing with win_size=700, stride=350, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7324  |  test: 2162
               →  train: 166 subjects (5702 windows)  |  val: 42 subjects (1622 windows)

Early stopping in epoch 63. Best F1: 0.9118

Val F1: 0.9118  |  Test F1: 0.8850
Checkpoint saved → ../checkpoints/free_raw_win700_stride350_normwindow\model.pt

================================

Processing with win_size=700, stride=350, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 7324  |  test: 2162
               →  train: 166 subjects (5702 windows)  |  val: 42 subjects (1622 windows)

Early stopping in epoch 43. Best F1: 0.9076

Val F1: 0.9076  |  Test F1: 0.8827
Checkpoint saved → ../checkpoints/free_raw_win700_stride350_normsubj\model.pt

================================

Processing with win_size=700, stride=175, process=raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14112  |  test: 4187
               →  train: 166 subjects (11004 windows)  |  val: 42 subjects (3108 windows)

Early stopping in epoch 58. Best F1: 0.9115

Val F1: 0.9115  |  Test F1: 0.8854
Checkpoint saved → ../checkpoints/raw_win700_stride175_normwindow\model.pt

================================

Processing with win_size=700, stride=175, process=raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14112  |  test: 4187
               →  train: 166 subjects (11004 windows)  |  val: 42 subjects (3108 windows)

Early stopping in epoch 48. Best F1: 0.8987

Val F1: 0.8987  |  Test F1: 0.8717
Checkpoint saved → ../checkpoints/raw_win700_stride175_normsubj\model.pt

================================

Processing with win_size=700, stride=175, process=free_raw, norm=window
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14112  |  test: 4187
               →  train: 166 subjects (11004 windows)  |  val: 42 subjects (3108 windows)

Early stopping in epoch 66. Best F1: 0.9124

Val F1: 0.9124  |  Test F1: 0.8856
Checkpoint saved → ../checkpoints/free_raw_win700_stride175_normwindow\model.pt

================================

Processing with win_size=700, stride=175, process=free_raw, norm=subj
Trials descartados: 10 ['HS_2_1', 'KOA_17_3', 'KOA_17_4', 'PD_6_4', 'PD_6_5', 'RIL_24_6', 'RIL_24_7', 'RIL_24_9', 'RIL_31_12', 'RIL_42_2'] | sujetos con datos: 260
Subject split  →  train+val: 208 subjects  |  test: 52 subjects
Window split   →  train+val: 14112  |  test: 4187
               →  train: 166 subjects (11004 windows)  |  val: 42 subjects (3108 windows)

Early stopping in epoch 37. Best F1: 0.9051

Val F1: 0.9051  |  Test F1: 0.8727
Checkpoint saved → ../checkpoints/free_raw_win700_stride175_normsubj\model.pt

================================


Done. 96 combinations trained.

# Results comparison

In [4]:
results_df = pd.DataFrame(results)
results_df = results_df.sort_values("val_f1", ascending=False).reset_index(drop=True)
results_df

,win_size,stride,overlap,process,norm,n_subjects,n_windows,val_f1,test_f1,checkpoint
0,400,100,0.75,raw,window,260,35562,0.917324,0.888501,../checkpoints/raw_win400_stride100_normwindow
1,400,200,0.50,raw,window,260,18126,0.917086,0.887998,../checkpoints/raw_win400_stride200_normwindow
2,200,50,0.75,raw,window,260,75840,0.916827,0.895212,../checkpoints/raw_win200_stride50_normwindow
3,200,50,0.75,free_raw,window,260,75840,0.916700,0.894765,../checkpoints/free_raw_win200_stride50_normwi...
4,400,300,0.25,free_raw,window,260,12298,0.916178,0.890164,../checkpoints/free_raw_win400_stride300_normw...
...,...,...,...,...,...,...,...,...,...,...
91,50,37,0.25,free_raw,window,260,107702,0.893584,0.866566,../checkpoints/free_raw_win50_stride37_normwindow
92,50,37,0.25,raw,subj,260,107702,0.892107,0.862056,../checkpoints/raw_win50_stride37_normsubj
93,50,50,0.00,raw,window,260,79878,0.890124,0.864260,../checkpoints/raw_win50_stride50_normwindow
94,50,50,0.00,free_raw,window,260,79878,0.887560,0.856792,../checkpoints/free_raw_win50_stride50_normwindow
95,50,50,0.00,raw,subj,260,79878,0.886631,0.865857,../checkpoints/raw_win50_stride50_normsubj

In [5]:
best_row = results_df.iloc[0]
print("Best configuration (selected by val_f1):")
print(best_row)
print(f"\n--> Reported test_f1 for this configuration: {best_row['test_f1']:.4f}")

Best configuration (selected by val_f1):
win_size                                                 400
stride                                                   100
overlap                                                 0.75
process                                                  raw
norm                                                  window
n_subjects                                               260
n_windows                                              35562
val_f1                                              0.917324
test_f1                                             0.888501
checkpoint    ../checkpoints/raw_win400_stride100_normwindow
Name: 0, dtype: object

--> Reported test_f1 for this configuration: 0.8885

In [6]:
pivot = results_df.pivot_table(index=["win_size", "stride"], columns="process", values="val_f1")
pivot["free_raw - raw"] = pivot["free_raw"] - pivot["raw"]
pivot.sort_values("free_raw - raw", ascending=False)

process          free_raw       raw  free_raw - raw
win_size stride
500      375     0.911509  0.904127        0.007382
         125     0.912587  0.905335        0.007252
         250     0.912326  0.905466        0.006859
700      350     0.909711  0.903652        0.006059
400      300     0.913775  0.908155        0.005620
700      700     0.910328  0.905241        0.005087
         525     0.909379  0.904539        0.004840
500      500     0.911778  0.907301        0.004477
200      200     0.909722  0.905349        0.004373
         100     0.911338  0.907202        0.004136
400      200     0.912831  0.909042        0.003789
700      175     0.908726  0.905131        0.003595
200      150     0.911917  0.908645        0.003273
50       50      0.890850  0.888378        0.002472
100      100     0.904141  0.901900        0.002240
         50      0.907694  0.905668        0.002026
200      50      0.913552  0.911698        0.001855
100      75      0.907343  0.905699        0.001644
400      400     0.910743  0.909300        0.001443
50       37      0.894304  0.892886        0.001418
100      25      0.910428  0.909041        0.001387
50       12      0.899727  0.898710        0.001016
400      100     0.911145  0.910646        0.000499
50       25      0.896454  0.896333        0.000120

In [7]:
subject_sets = {}
for r in results:
    ckpt_file = os.path.join(r["checkpoint"], "model.pt")
    if not os.path.exists(ckpt_file):
        continue
    import torch
    ckpt = torch.load(ckpt_file, map_location='cpu', weights_only=False)
    subject_sets[(r["win_size"], r["stride"], r["process"])] = set(ckpt["test_subjects"])

reference_key, reference_set = next(iter(subject_sets.items()))
mismatches = {k: v for k, v in subject_sets.items() if v != reference_set}

if mismatches:
    print(f"WARNING: {len(mismatches)} configuration(s) have a different test-subject split than {reference_key}.")
    print("This means n_subjects differs across configs (likely due to short trials being dropped")
    print("at larger window_size), so val_f1/test_f1 are not perfectly comparable across all rows.")
    for k in list(mismatches.keys())[:10]:
        print("  -", k)
else:
    print("OK: all configurations share the exact same test-subject split.")

OK: all configurations share the exact same test-subject split.